#!/usr/bin/env bash
# E&C Super Master System — one-command VPS setup (unified deployment)
#
# Stands up the whole estate as ONE Node process on ONE port: clones the five
# repos, installs dependencies, generates secrets into Final-system/.env,
# prepares each database, builds everything, and starts the unified server
# under PM2. Requires: git, Node.js 20+ (with npm), and network access to
# GitHub. Caddy + DNS are the only manual steps (printed at the end).
#
#   curl -fsSL https://raw.githubusercontent.com/yohan114/Final-system/main/deploy/setup-vps.sh | bash
#     — or —
#   bash Final-system/deploy/setup-vps.sh
#
# Options (flags or env):
#   EC_ROOT=/opt/ec          where the five checkouts live   (default /opt/ec)
#   GITHUB_OWNER=yohan114    GitHub account holding the repos
#   PORTAL_DOMAIN=portal.ec-workshops.online   the ONE main link
#   --no-clone     use existing checkouts in EC_ROOT (skip git clone/pull)
#   --no-install   skip npm install steps
#   --no-build     skip build steps
#   --no-start     prepare everything but do not start PM2
#
# Existing data is never touched: .env is only generated when missing, and
# each system's database is only migrated/seeded when its DB file is absent.

set -euo pipefail

EC_ROOT="${EC_ROOT:-/opt/ec}"
GITHUB_OWNER="${GITHUB_OWNER:-yohan114}"
PORTAL_DOMAIN="${PORTAL_DOMAIN:-portal.ec-workshops.online}"
DO_CLONE=1 DO_INSTALL=1 DO_BUILD=1 DO_START=1
for arg in "$@"; do
  case "$arg" in
    --no-clone) DO_CLONE=0 ;;
    --no-install) DO_INSTALL=0 ;;
    --no-build) DO_BUILD=0 ;;
    --no-start) DO_START=0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

REPOS=(Final-system Fuel-System-V2 Main-stros-system Store-Database oil-stock-book)
PORTAL="$EC_ROOT/Final-system"
say()  { printf '\n\033[1m== %s ==\033[0m\n' "$*"; }
note() { printf '   %s\n' "$*"; }
gen()  { node -e "console.log(require('crypto').randomBytes(24).toString('base64url'))"; }

say "Checking prerequisites"
command -v git >/dev/null || { echo "git is required"; exit 1; }
command -v node >/dev/null || { echo "Node.js 20+ is required"; exit 1; }
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 20 ] || { echo "Node.js 20+ required (found $(node -v))"; exit 1; }
note "git $(git --version | awk '{print $3}') · node $(node -v) · EC_ROOT=$EC_ROOT · domain=$PORTAL_DOMAIN"

if [ "$DO_CLONE" = 1 ]; then
  say "Cloning / updating the five repositories"
  mkdir -p "$EC_ROOT"
  for r in "${REPOS[@]}"; do
    if [ -d "$EC_ROOT/$r/.git" ]; then
      note "$r exists — pulling latest default branch"
      git -C "$EC_ROOT/$r" pull --ff-only
    else
      git clone "https://github.com/$GITHUB_OWNER/$r.git" "$EC_ROOT/$r"
    fi
  done
else
  say "Using existing checkouts in $EC_ROOT (--no-clone)"
  for r in "${REPOS[@]}"; do [ -d "$EC_ROOT/$r" ] || { echo "missing $EC_ROOT/$r"; exit 1; }; done
fi

if [ "$DO_INSTALL" = 1 ]; then
  say "Installing dependencies"
  for d in "${REPOS[@]}"; do
    if [ ! -d "$EC_ROOT/$d/node_modules" ]; then
      note "npm install — $d"
      (cd "$EC_ROOT/$d" && npm install --no-audit --no-fund)
    else
      note "$d: node_modules present — skipping"
    fi
  done
  if [ ! -d "$EC_ROOT/oil-stock-book/client/node_modules" ]; then
    note "npm install — oil-stock-book/client"
    (cd "$EC_ROOT/oil-stock-book/client" && npm install --no-audit --no-fund)
  fi
fi

say "Configuring Final-system/.env (single config for the whole box)"
ENV_FILE="$PORTAL/.env"
if [ -f "$ENV_FILE" ]; then
  note ".env exists — keeping it untouched"
else
  ADMIN_PW="$(gen)"
  cat > "$ENV_FILE" <<ENV
# Generated by setup-vps.sh on $(date -u +%FT%TZ) — one config for the whole box.
DATABASE_URL="file:$PORTAL/data/portal.db"
PORTAL_AUTH_SECRET="$(gen)"
SEED_PORTAL_ADMIN_PASSWORD="$ADMIN_PW"

# One main link, four subs
PORTAL_PUBLIC_DOMAIN="$PORTAL_DOMAIN"

# Unified server: health/KPI polling through the in-process channel
FUEL_BASE_URL="http://127.0.0.1:4400/__sys/fuel"
MAINSTORES_BASE_URL="http://127.0.0.1:4400/__sys/mainstores"
WORKSHOP_BASE_URL="http://127.0.0.1:4400/__sys/workshop"
OILBOOK_BASE_URL="http://127.0.0.1:4400/__sys/oilbook"

# Per-system portal tokens (one value configures both sides in unified mode)
FUEL_PORTAL_TOKEN="$(gen)"
MAINSTORES_PORTAL_TOKEN="$(gen)"
WORKSHOP_PORTAL_TOKEN="$(gen)"
OILBOOK_PORTAL_TOKEN="$(gen)"

# System auth secrets (the systems' own .env files may override with their own)
FUEL_AUTH_SECRET="$(gen)"
MAINSTORES_AUTH_SECRET="$(gen)"

CRON_SECRET="$(gen)"
COOKIE_SECURE="true"
BUSINESS_TZ="Asia/Colombo"
ENV
  chmod 600 "$ENV_FILE"
  note "generated $ENV_FILE (mode 600)"
  note "PORTAL ADMIN PASSWORD (save it now, then change after first login): $ADMIN_PW"
fi

say "Preparing databases (only where missing — existing data untouched)"
if [ ! -f "$PORTAL/data/portal.db" ]; then
  note "portal: migrate + seed"
  (cd "$PORTAL" && npx prisma migrate deploy && npm run seed)
else
  note "portal: DB exists — re-running seed to refresh system links (idempotent)"
  (cd "$PORTAL" && npm run seed)
fi
if [ ! -f "$EC_ROOT/Fuel-System-V2/data/app.db" ]; then
  note "fuel: migrate + seed (set SEED_ADMIN_PASSWORD beforehand to choose the admin password)"
  (cd "$EC_ROOT/Fuel-System-V2" && npx prisma migrate deploy && npx tsx prisma/seed.ts)
else
  note "fuel: DB exists — applying any pending migrations"
  (cd "$EC_ROOT/Fuel-System-V2" && npx prisma migrate deploy)
fi
if [ ! -f "$EC_ROOT/Main-stros-system/dev.db" ]; then
  note "mainstores: schema push + seed"
  (cd "$EC_ROOT/Main-stros-system" && npx prisma db push && node prisma/seed.js)
else
  note "mainstores: DB exists — leaving as-is"
fi
note "workshop: creates/seeds its own DB on first boot (import legacy data with 'npm run migrate' if you have tracker_data.json)"
note "oil book: creates/seeds its own DB on first boot (auto-imports data/source/*.xlsx when present)"

if [ "$DO_BUILD" = 1 ]; then
  say "Building production bundles"
  for d in Final-system Fuel-System-V2 Main-stros-system; do
    note "next build — $d"
    (cd "$EC_ROOT/$d" && npx prisma generate >/dev/null 2>&1 || true; npm run build)
  done
  note "vite build — oil-stock-book/client"
  (cd "$EC_ROOT/oil-stock-book/client" && npm run build)
fi

if [ "$DO_START" = 1 ]; then
  say "Starting the unified server under PM2"
  command -v pm2 >/dev/null || { note "installing pm2"; npm install -g pm2; }
  EC_ROOT="$EC_ROOT" pm2 start "$PORTAL/deploy/ecosystem.config.js"
  pm2 save
  note "enable boot start with:  pm2 startup   (follow its printed instruction)"
fi

say "Done — remaining manual steps"
cat <<STEPS
  1. DNS: point  $PORTAL_DOMAIN  and  *.$PORTAL_DOMAIN  at this machine.
  2. TLS proxy:  caddy start --config $PORTAL/deploy/Caddyfile
     (install: https://caddyserver.com/docs/install)
  3. Open  https://$PORTAL_DOMAIN  — sign in with the portal admin password
     printed above (rotate it, and every seeded system password, on first login).
  Health check without DNS:  curl -H "Host: fuel.$PORTAL_DOMAIN" http://127.0.0.1:4400/api/health
STEPS
