#!/usr/bin/env bash
# E&C Super Master System — one-command VPS setup (ONE repo, ONE process)
#
# The whole estate lives in this single repository: the Master Portal at the
# root and the four systems in apps/{fuel,stores,workshop,oilbook}, all served
# by one Node process (server/unified.mjs, port 4400). This script clones the
# repo, installs dependencies, generates secrets into .env, prepares each
# database, builds everything, and starts the unified server under PM2.
# Requires: git, Node.js 20+ (with npm). Caddy + DNS are the only manual
# steps (printed at the end).
#
#   curl -fsSL https://raw.githubusercontent.com/yohan114/Final-system/main/deploy/setup-vps.sh | bash
#     — or —
#   bash Final-system/deploy/setup-vps.sh
#
# Options (flags or env):
#   EC_ROOT=/opt/ec          where the checkout lives        (default /opt/ec)
#   GITHUB_OWNER=yohan114    GitHub account holding the repo
#   PORTAL_DOMAIN=portal.ec-workshops.online   the ONE main link
#   --no-clone     use the existing checkout (skip git clone/pull)
#   --no-install   skip npm install steps
#   --no-build     skip build steps
#   --no-start     prepare everything but do not start PM2
#
# Existing data is never touched: .env is only generated when missing, and
# each system's database is only migrated/seeded when its DB file is absent.

set -euo pipefail

EC_ROOT="${EC_ROOT:-/opt/ec}"
GITHUB_OWNER="${GITHUB_OWNER:-yohan114}"
PORTAL_DOMAIN="${PORTAL_DOMAIN:-portal.ec-workshops.online}"
DO_CLONE=1 DO_INSTALL=1 DO_BUILD=1 DO_START=1
for arg in "$@"; do
  case "$arg" in
    --no-clone) DO_CLONE=0 ;;
    --no-install) DO_INSTALL=0 ;;
    --no-build) DO_BUILD=0 ;;
    --no-start) DO_START=0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

PORTAL="$EC_ROOT/Final-system"
APP_DIRS=("$PORTAL" "$PORTAL/apps/fuel" "$PORTAL/apps/stores" "$PORTAL/apps/workshop" "$PORTAL/apps/oilbook")
say()  { printf '\n\033[1m== %s ==\033[0m\n' "$*"; }
note() { printf '   %s\n' "$*"; }
gen()  { node -e "console.log(require('crypto').randomBytes(24).toString('base64url'))"; }

say "Checking prerequisites"
command -v git >/dev/null || { echo "git is required"; exit 1; }
command -v node >/dev/null || { echo "Node.js 20+ is required"; exit 1; }
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 20 ] || { echo "Node.js 20+ required (found $(node -v))"; exit 1; }
note "git $(git --version | awk '{print $3}') · node $(node -v) · EC_ROOT=$EC_ROOT · domain=$PORTAL_DOMAIN"

if [ "$DO_CLONE" = 1 ]; then
  say "Cloning / updating the repository (one repo holds everything)"
  mkdir -p "$EC_ROOT"
  if [ -d "$PORTAL/.git" ]; then
    note "Final-system exists — pulling latest default branch"
    git -C "$PORTAL" pull --ff-only
  else
    git clone "https://github.com/$GITHUB_OWNER/Final-system.git" "$PORTAL"
  fi
else
  say "Using existing checkout in $PORTAL (--no-clone)"
  [ -d "$PORTAL" ] || { echo "missing $PORTAL"; exit 1; }
fi
for d in "${APP_DIRS[@]}"; do [ -d "$d" ] || { echo "missing $d — incomplete checkout?"; exit 1; }; done

if [ "$DO_INSTALL" = 1 ]; then
  say "Installing dependencies (each app keeps its own node_modules)"
  for d in "${APP_DIRS[@]}" "$PORTAL/apps/oilbook/client"; do
    if [ ! -d "$d/node_modules" ]; then
      note "npm install — ${d#$EC_ROOT/}"
      (cd "$d" && npm install --no-audit --no-fund)
    else
      note "${d#$EC_ROOT/}: node_modules present — skipping"
    fi
  done
fi

say "Configuring $PORTAL/.env (single config for the whole box)"
ENV_FILE="$PORTAL/.env"
if [ -f "$ENV_FILE" ]; then
  note ".env exists — keeping it untouched"
else
  ADMIN_PW="$(gen)"
  cat > "$ENV_FILE" <<ENV
# Generated by setup-vps.sh on $(date -u +%FT%TZ) — one config for the whole box.
DATABASE_URL="file:$PORTAL/data/portal.db"
PORTAL_AUTH_SECRET="$(gen)"
SEED_PORTAL_ADMIN_PASSWORD="$ADMIN_PW"

# One main link, four subs
PORTAL_PUBLIC_DOMAIN="$PORTAL_DOMAIN"

# Unified server: health/KPI polling through the in-process channel
FUEL_BASE_URL="http://127.0.0.1:4400/__sys/fuel"
MAINSTORES_BASE_URL="http://127.0.0.1:4400/__sys/mainstores"
WORKSHOP_BASE_URL="http://127.0.0.1:4400/__sys/workshop"
OILBOOK_BASE_URL="http://127.0.0.1:4400/__sys/oilbook"

# Per-system portal tokens (one value configures both sides in unified mode)
FUEL_PORTAL_TOKEN="$(gen)"
MAINSTORES_PORTAL_TOKEN="$(gen)"
WORKSHOP_PORTAL_TOKEN="$(gen)"
OILBOOK_PORTAL_TOKEN="$(gen)"

# Single sign-on: portal login opens each system already signed in
FUEL_SSO_SECRET="$(gen)"
MAINSTORES_SSO_SECRET="$(gen)"
WORKSHOP_SSO_SECRET="$(gen)"
OILBOOK_SSO_SECRET="$(gen)"

# System auth secrets
FUEL_AUTH_SECRET="$(gen)"
MAINSTORES_AUTH_SECRET="$(gen)"

CRON_SECRET="$(gen)"
COOKIE_SECURE="true"
BUSINESS_TZ="Asia/Colombo"
ENV
  chmod 600 "$ENV_FILE"
  note "generated $ENV_FILE (mode 600)"
  note "PORTAL ADMIN PASSWORD (save it now, then change after first login): $ADMIN_PW"
fi

say "Preparing databases (only where missing — existing data untouched)"
if [ ! -f "$PORTAL/data/portal.db" ]; then
  note "portal: migrate + seed"
  (cd "$PORTAL" && npx prisma migrate deploy && npm run seed)
else
  note "portal: DB exists — re-running seed to refresh system links (idempotent)"
  (cd "$PORTAL" && npm run seed)
fi
if [ ! -f "$PORTAL/apps/fuel/data/app.db" ]; then
  note "fuel: migrate + seed (set SEED_ADMIN_PASSWORD beforehand to choose the admin password)"
  (cd "$PORTAL/apps/fuel" && npx prisma migrate deploy && npx tsx prisma/seed.ts)
else
  note "fuel: DB exists — applying any pending migrations"
  (cd "$PORTAL/apps/fuel" && npx prisma migrate deploy)
fi
if [ ! -f "$PORTAL/apps/stores/dev.db" ]; then
  note "stores: schema push + seed"
  (cd "$PORTAL/apps/stores" && npx prisma db push && node prisma/seed.js)
else
  note "stores: DB exists — leaving as-is"
fi
note "workshop: creates/seeds its own DB on first boot (import legacy data with 'npm run migrate' if you have tracker_data.json)"
note "oil book: creates/seeds its own DB on first boot (auto-imports data/source/*.xlsx when present)"

if [ "$DO_BUILD" = 1 ]; then
  say "Building production bundles"
  for d in "$PORTAL" "$PORTAL/apps/fuel" "$PORTAL/apps/stores"; do
    note "next build — ${d#$EC_ROOT/}"
    (cd "$d" && npx prisma generate >/dev/null 2>&1 || true; npm run build)
  done
  note "vite build — apps/oilbook/client"
  (cd "$PORTAL/apps/oilbook/client" && npm run build)
fi

say "Merging all systems' history into the master database"
(cd "$PORTAL" && npm run import:history) || note "history import skipped (re-run later with: npm run import:history)"

if [ "$DO_START" = 1 ]; then
  say "Starting the unified server under PM2"
  command -v pm2 >/dev/null || { note "installing pm2"; npm install -g pm2; }
  EC_ROOT="$EC_ROOT" pm2 start "$PORTAL/deploy/ecosystem.config.js"
  pm2 save
  note "enable boot start with:  pm2 startup   (follow its printed instruction)"
fi

say "Done — remaining manual steps"
cat <<STEPS
  1. DNS: point  $PORTAL_DOMAIN  and  *.$PORTAL_DOMAIN  at this machine.
  2. TLS proxy:  caddy start --config $PORTAL/deploy/Caddyfile
     (install: https://caddyserver.com/docs/install)
  3. Open  https://$PORTAL_DOMAIN  — sign in with the portal admin password
     printed above (rotate it, and every seeded system password, on first login).
  Health check without DNS:  curl -H "Host: fuel.$PORTAL_DOMAIN" http://127.0.0.1:4400/api/health
STEPS
